name: build
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x

      - name: Build
        run: |
          dotnet publish -c Release -o binaries
          zip -r binaries.zip binaries
          
      # Get the assembly version, use this as the tag.
      # That way, to do a new release, just update the assembly version on the next commit
      - name: Get Assembly Version
        id: get_version
        uses: jasondavis303/net-sdk-proj-file-version@v1.0.1
        with: 
          PROJ_FILE: s3u/s3u.csproj        
      
      - name: Tag and Release
        uses: jasondavis303/tag-and-release-and-upload@1.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          
          # Use the version from the previous step
          version: v${{ steps.get_version.outputs.ASSEMBLY_VERSION }}
          
          assets: '[ "binaries.zip" ]'
          overwrite: false          