name: build
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x

      - name: Build
        run: |
          ./tsv --xml-files s3u/s3u.csproj --env-file $GITHUB_ENV
          dotnet publish -r win-x64 -p:PublishSingleFile=true --no-self-contained -c release -o publish
          dotnet publish -r linux-x64 -p:PublishSingleFile=true --no-self-contained -c release -o publish
          dotnet pack -c release -o nuget
          dotnet nuget push "nuget/*.nupkg" --skip-duplicate -k ${{secrets.NUGET_KEY}} -s https://api.nuget.org/v3/index.json

      - name: Tag and Release
        uses: jasondavis303/tag-and-release-and-upload@v1.4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }} 
          version: v${{ env.TIMESTAMP_VERSION }}          
          assets: '[ "./publish/s3u.exe", "./publish/s3u" ]'
          overwrite: true
